name: CI

on:
  workflow_dispatch:
  pull_request:

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.11', '3.12']
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: true
      - name: Install dependencies
        run: uv sync --all-extras --group dev --frozen
      - name: Run lint
        run: uv run pre-commit run --all-files
      - name: Run test
        run: uv run pytest tests/
      - name: Run running tests
        run: |
           uv run python -m github_poster github --github_user_name yihong0618
           uv run python -m github_poster multiple --types "github, dota2" --github_user_name piglei --dota2_id 70388657 --year 2018-2022
